name: check format
on:
  push:
  pull_request:
jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check formatting
        run: make check-format
